---
title: "Prepare data models"
author: "Max Lindmark & Francesca Vitale"
date: today
date-format: iso
toc: true
format: 
  html:
    page-layout: full
    embed-resources: true
knitr: 
  opts_chunk:
    fig.align: center
    out-width: 100%
editor: source
---

```{r load libraries}
#| message: false
#| warning: false

# Load libraries
library(tidyverse)
library(tidylog)
library(sdmTMB)
library(patchwork)
library(viridis)
library(RColorBrewer)
library(modelr)
library(ggstats)
library(ggspatial)
library(marmap)
library(ncdf4)
library(crayon)
library(tidyterra)
library(tidync)
library(ggsidekick); theme_set(theme_sleek())

home <- here::here()
```

## Read and prepare data

```{r}
d <- read.csv(paste0(home, "/data/Trawl Surveys Zincl (L)_2026.csv"), sep = ";", dec = ",") |> 
  janitor::clean_names() |> 
  filter(subdiv <= 21) |> 
  filter(validity == "V") |> 
  mutate(haul_id = paste(year, quarter, month, haul)) |> 
  # New names from 2025
  rename(swept_area = swept_area_km2,
         duration = duration_min) |> 
  mutate(median_swept = median(swept_area, na.rm = TRUE), .by = year) |>
  mutate(swept_area = ifelse(is.na(swept_area), median_swept, swept_area),
         kg_hour = replace_na(kg_hour, 0),
         kg = kg_hour * (duration / 60),
         density = kg / swept_area) |> 
  distinct(haul_id, .keep_all = TRUE) |> 
  mutate(upr_cut = quantile(density, probs = 0.995, na.rm = TRUE), .by = quarter) |> 
  filter(density < upr_cut) |> 
  dplyr::select(date, year, quarter, month, subdiv, lat, long, density) |> 
  mutate(lat = floor(lat/100)+(lat-100*floor(lat/100))/60,
         lon = floor(long/100)+(long-100*floor(long/100))/60,
         lat = ifelse(lat<0,-1*lat,lat),
         lon = ifelse(long<0,-1*lon,lon)) |> 
  add_utm_columns(ll_names = c("lon", "lat"))
```

### Add covariates
Add depth

```{r}
depth_box <- getNOAA.bathy(min(d$lon) - .1, max(d$lon) + .1, min(d$lat)  - .1, max(d$lat) + .1)

d$depth <- get.depth(depth_box, x=d$lon, y=d$lat, locator=F)$depth*(-1)
```

```{r}
d %>% 
  filter(year < 2011) |> 
  filter(!quarter == 1) |> 
  arrange(desc(density))

# TEST
d %>% 
  filter(year < 2022) |> 
  summarise(dens = mean(density), .by = c(year, quarter)) %>% 
  ggplot(aes(year, dens, color = as.factor(quarter))) + 
  geom_line() +
  scale_color_brewer(palette = "Set1", name = "Quarter") +
  theme(legend.position = "bottom") +
  labs(subtitle = "Mean density in data",
       x = "Year", y = "Density (kg/km2)")
```

Add temperature

```{r}
# SBT? 
# https://data.marine.copernicus.eu/product/GLOBAL_MULTIYEAR_PHY_001_030/description
# d <- d |>
#   filter(year >= 1993) |> 
#   mutate(year_month = paste(year, month, sep = "_"))
# 
# read_trim_nc <- function(file_path){
#   
#   tidync(file_path) |>
#     hyper_tibble() |>
#     mutate(date = as.Date(as.POSIXct(time, origin = "1970-01-01")),
#            year = year(date),
#            month = month(date),
#            day = day(date),
#            year = year(date),
#            year_month = paste(year, month, sep = "_")) |> 
#     rename(lon = longitude,
#            lat = latitude,
#            temp = bottomT) |> 
#     filter(year_month %in% c(unique(d$year_month)) & day == 1 & lon > 7 & lon < 15 & lat > 54 & lat < 61)
# }
# 
# print(
#   nc_open(paste0(home, "/data/covariates/sbt/cmems_mod_glo_phy_my_0.083deg_P1D-m_1758698322450.nc")))
# 
# st_tibble5 <- read_trim_nc(
#   paste0(home, "/data/covariates/sbt/cmems_mod_glo_phy_my_0.083deg_P1D-m_1758698322450.nc"))
# 
# ggplot() +
#   geom_raster(data = st_tibble5, aes(lon, lat, fill = temp)) +
#   facet_wrap(~year)
# 
# # Loop through all year/month combos, extract the temperatures at the data locations
# temp_list <- list()
# 
# for (i in unique(d$year_month)) {
#   d_sub <- filter(d, year_month == i)
#   temp_tibble_sub <- filter(st_tibble5, year_month == i)
# 
#   # Convert to raster
#   temp_raster <- as_spatraster(temp_tibble_sub,
#     xycols = 2:3,
#     crs = "WGS84", digits = 3
#   )
# 
#   # Extract from raster
#   d_sub$temp <- terra::extract(
#     temp_raster$temp,
#     d_sub |> dplyr::select(lon, lat)
#   )$thetao
# 
#   # Save
#   temp_list[[i]] <- d_sub
# }
# 
# d_temp <- bind_rows(temp_list)
```

```{r}
# New approach based on ensemble forecast
d <- d |>
  filter(year >= 1993) |> 
  mutate(year_month = paste(year, month, sep = "_"))

read_trim_nc <- function(file_path){
  
  tidync(file_path) |>
    hyper_tibble() |>
    mutate(date = as.Date(time, origin = "1993-01-01"),
           year = year(date),
           month = month(date),
           day = day(date),
           year = year(date),
           year_month = paste(year, month, sep = "_")) |> 
    filter(year_month %in% c(unique(d$year_month)) & day == 1 & lon > 7 & lon < 15 & lat > 54 & lat < 61 & percentiles == 50)
}

print(
  nc_open(
    "/Users/maxlindmark/Dropbox/max-work/R/larvae-sizes/data/covariates/ensemble/thetao_ensemble_sd+ba_surface_depth_5.0_perc_ssp245.nc"))

st_tibble5 <- read_trim_nc("/Users/maxlindmark/Dropbox/max-work/R/larvae-sizes/data/covariates/ensemble/thetao_ensemble_sd+ba_surface_depth_5.0_perc_ssp245.nc")

# Loop through all year/month combos, extract the temperatures at the data locations
temp_list <- list()

for (i in unique(d$year_month)) {
  d_sub <- filter(d, year_month == i)
  temp_tibble_sub <- filter(st_tibble5, year_month == i)

  # Convert to raster
  temp_raster <- as_spatraster(temp_tibble_sub,
    xycols = 3:4,
    crs = "WGS84", digits = 3
  )

  # Extract from raster
  d_sub$temp <- terra::extract(
    temp_raster$thetao,
    d_sub |> dplyr::select(lon, lat)
  )$thetao

  # Save
  temp_list[[i]] <- d_sub
}

d_temp <- bind_rows(temp_list)
```

### Save

```{r}
write_csv(d_temp, paste0(home, "/data/clean/trawl.csv"))
```


